### ISSUE TITLE
handle_info doesn't receive any data, but device is connected correctly

### ISSUE THREAD

**Issue by bartekupartek** [bitgamma/elixir_serial#2]
I encountered next problem and posted on [stackowerflow](http://stackoverflow.com/q/33291009/707729), according to new readme I connected correctly to serialport my device added handle_info listener, but it doesn't recieve any data. I've tested the device with the same parameters in ruby serialport and it is working well. Do you have any idea?

**Comment by benlangfeld** [comment]
Did you arrive at a resolution for this?

**Comment by bitgamma** [comment]
The issue was not in the library but in its usage. Please let's use either Elixir mailing list or StackOverflow for support.
