### ISSUE TITLE
handle_info() not always receives a message entirely

### ISSUE THREAD

**Issue by bartekupartek** [bitgamma/elixir_serial#3]
I'm trying to handle RFID SEN-09963 ids via serialport and I've encountered difficulty that `handle_info()` receives id not entirely. It may be associated with Serial setting?
In documentation I've read that device has none parity, data bits is 8 and stop bits is 1.
How to workaround this?

setup:

```
    {:ok, serial} = Serial.start_link
    Serial.open(serial, "/dev/cu.usbserial-A5026NYN")
    Serial.set_speed(serial, 9600)
    Serial.connect(serial)
```

handle_info():

```
  def handle_info({:elixir_serial, serial, data}, state) do
    Logger.debug "received :data #{data}"
    {:noreply, state}
  end
```

log:

```
[debug] received :data
[debug] received :data 7A005AFA518B

[debug] received :data
[debug] received :data 7
[debug] received :data A005AFA518B

[debug] received :data
[debug] received :data 7A005AFA518B

[debug] received :data
[debug] received :data 7A005AFA518
[debug] received :data B
```

I've tryed to figure out why I get multiple messages, this is not related with bits, I set manually in set_tty_speed() and result is the same:

```
  ttymodes.c_cflag |= CS8;         /* enable eight bit chars */
  ttymodes.c_cflag &= ~PARENB;     /* disable input parity check */
  ttymodes.c_cflag &= ~CSTOPB;     /* enable 1 stop bit */
```

I've compiled serial.c, and it seems that it isn't waiting for whole message, it cut ids as in handle_info()

```
./compiledserial
7AB
AFA518BA518B
5AFA518B
8B
7A005AF
```

**Comment by bitgamma** [comment]
I do not think this is a bug, it is more likely that the device does not send the data all at once. If the ids are of fixed length, the solution would be to concatenate the data until it reaches the needed length in your handle_info function (for example by storing the partial id in the state). When the data is finally complete, you can do whatever you need to do with it.
