### ISSUE TITLE
Return error or crash on failure to connect

### ISSUE THREAD

**Issue by TattdCodeMonkey** [bitgamma/elixir_serial#9]
Currently if I call `Serial.connect` and there is a problem there is no way of knowing from the calling process. I see a message in `iex` but the `Serial.connect` call always return `:ok` and a failed command does not crash the `Serial` `GenServer`. 

To reproduce just try to open a resource that does not exist.

Ideally one of three things would happen:

``` elixir
# Option 1
Serial.open("/dev/myport")
Serial.set_speed(9600)

case Serial.connect(pid) do
  :ok -> Logger.info("Yay! we have a serial port")
  {:error, _reason} -> Logger.warn(":( no serial port")
end
```

``` elixir
#Option 2
:ok = Serial.connect(pid) 
# Serial GenServer crashes on failure to open 
# this is what erlang-serial does
```

``` elixir
#Option 3
try do
  :ok = Serial.connect(pid)
  Logger.info("Yay!! serial port")
rescue
  RuntimeError -> Logger.warn(":'( no serial port")
```

Personally I like options 1 or 3. Option 2 relies on running both `Serial` and the calling server under the same Sup, or monitoring the `Serial` `GenServer` from your calling server. Which is still workable though.

**Comment by bitgamma** [comment]
Indeed, error handling is missing. PR would be very welcome

**Comment by TattdCodeMonkey** [comment]
I can try to put something together this week. Any preference between throwing `raise` and named tuple `{:error, "failure reason"}`?

**Comment by bitgamma** [comment]
I would go for {:error, "reason"}

**Comment by TattdCodeMonkey** [comment]
I dove in and did a lot of testing last night. To get better error handling would require including `erlcmd.h` in the C code and doing a lot of overhauling there. Which is honestly a bit beyond me.

I was able to workaround my issue by trapping exits in my Serial handler module. Which i may just add an example to the README. 

something like

``` elixir
def init(_) do
  Process.flag(:trap_exit, true)
  {:ok, %{}}
end

def handle_info({:EXIT, pid, reason}, %{serial: pid} = state) do
  # handle Serial server exit
  {:noreply, %{}}
end
```

Also looking into the source some more it seems calling `Serial.connect` in the current example is a bit redundant. The following code works exactly the same:

``` elixir
{:ok, pid} = Serial.start_link

Serial.set_speed(pid, 57600)
Serial.open(pid, '/dev/ttyS0')
```

**Comment by TattdCodeMonkey** [comment]
A slightly related word of caution, I was testing with my FTDI cable as the serial port on OSX and tried to test a failure by removing the cable.... and that crashed my OS. And then later I had killed all the `Serial` processes but hadn't closed `iex` yet and removing the cable crashed the OS again. That could be a bug with the FTDI driver maybe, but thought it might be helpful to mention.
